# Generated by Django 4.2.4 on 2023-09-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SELLER', 'SELLER'), ('CUSTOMER', 'CUSTOMER')], max_length=50, verbose_name='роль пользователя'),
        ),
    ]
